### ISSUE TITLE
"Log in" for nøkkelvakter

### ISSUE THREAD

**Issue by ulfpip** [schpaa/nrpk-22#14]
Det står "Logg inn" nederst til venstre. Men, jeg må klikke på hus øverst til høyre for å logge inn. Ellers lettforståelig. Fint design:) Gradene i våttkortstigen ligger som "koder", ikke som riktige trinn i våttkortstigen (grunnkurs, teknikkurs, aktivitetsleder eller høyere)

**Comment by schpaa** [comment]
- [ ] Fullfør gradene i våttkortstigen
- [ ] Endre utformingen slik at det blir tydelig at det bare er hjørnene som er aktive og ikke noe annet (i header)
