### ISSUE TITLE
Noen ideer rundt båtlogg-panelet

### ISSUE THREAD

**Issue by schpaa** [schpaa/nrpk-22#21]
0. [video](https://www.youtube.com/watch?v=zRsZyhu_QnI)

1. initial-state
<img width="282" alt="image" src="https://user-images.githubusercontent.com/4696356/158766508-cb0d0c62-d627-49b4-8610-525787797f2e.png">

2. in-progress-not-enough-data
<img width="280" alt="image" src="https://user-images.githubusercontent.com/4696356/158766689-40726886-cd20-4934-aa3e-6ddbbce063c7.png">

3. in-progress-enough-data-but-diverging
<img width="283" alt="image" src="https://user-images.githubusercontent.com/4696356/158771133-4209185f-7853-4798-a89e-ce0597a3fcf4.png">

4. in-progress-about-to-complete
<img width="281" alt="image" src="https://user-images.githubusercontent.com/4696356/158766366-22d4fa3a-2923-4767-bf29-7a8e8d5de213.png">

**Comment by schpaa** [comment]
## Struktur:

Felter for 
- [ ] Skal du overnatte?
- [ ] Har du nøkkel? *Er du nøkkelvakt og logget inn med relevant konto kan du ikke endre dette feltet. Nøkkelen vil alltid vises. Du forventes mao at du bruker nøkkelen. Bruker du iPad'en på anlegget vil denne være assosiert med en annen konto og båtlogg-panelet vil ha en litt annen adferd, mer om dette senere.*
- [ ] Hvor mange voksne er det i denne gruppen?
- [ ] Hvor mange barn er det i denne gruppen? *Ungdom? Barn? Er det behov for å gjøre forskjell?*
- [ ] Numerisk tastatur som alltid er bundet til båtnummer-feltet.
- [ ] Legg til båt. Det er plass til 3 båter, er det flere blir vinduet utvidet og overskytende båter legges under.
- [ ] Fjern innhold i båtnummer-felt. *Samme knapp fjerner også det du har valgt av registrerte båter (markert med gult).*
- [ ] Nullstill skjema. Hold knappet inne i ca 1 sekund for å utføre, slik ungår vi feil ved løssluppent trykking.
- [ ] Registrere/avslutt.

### Spesielt
Det er en rekke spesial-tilstander som gjør at en registrering ikke er godkjent.
1. Minimum en båt, og denne må finnes. 
2. Er det et tall i båtnummer-feltet som ikke er komplett, eller som ikke har en tilsvarende båt, eller som ikke samsvarer med det som finnes i registrerings-listen, kan det ikke fullføres. (se bilde nr 3 i posten over).

**Comment by ulfpip** [comment]
Nydelig og enkelt design. Her ser jeg ikke telefonnummer?

En ting som jeg har savnet noen ganger er mulighet til å endre info mens
jeg er på vannet. Vanligste endring er legge til nøkkel i etterkant.

Ulf
