### ISSUE TITLE
HMS

### ISSUE THREAD

**Issue by ulfpip** [schpaa/nrpk-22#23]
Før vi kan la Eykt bli hjemmeside må vi ha HMS-håndbok tilgjengelig under NRPK, og vaktinstruks etc tilgjengelig under Nøkkelvakt.

**Comment by schpaa** [comment]
Vaktinstruks [eykt.nrpk.no/dokumenter/vaktinstruks](https://eykt.nrpk.no/dokumenter/vaktinstruks)
HMS-håndbok [eykt.nrpk.no/dokumenter/hms-håndbok](https://eykt.nrpk.no/dokumenter/hms-håndbok)
