### ISSUE TITLE
Forslag til ingress "Nøkkelvakt"

### ISSUE THREAD

**Issue by ulfpip** [schpaa/nrpk-22#37]
Nøkkelvaktene er en gruppe med over hundre frivillige medlemmer som betjener klubbens anlegg ved Nøklevann i klubbens åpningstider.

**Comment by schpaa** [comment]
Denne finnes som:

> Nøkkelvaktene er en gruppe med omtrent 130 frivillige medlemmer som betjener klubbens anlegg ved Nøklevann i klubbens åpningstider. Nøkkelvaktene hjelper medlemmene, sjekker medlemsskap og bidrar til sikkerheten i klubbens aktivitet.

**Comment by ulfpip** [comment]
Bra forslag. Den bruker vi
